version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: human_resources_service
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: {}